/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app-footer.vue')['default']
    AppHeader: typeof import('./components/app-header.vue')['default']
    Contact: typeof import('./components/contact.vue')['default']
    Counter: typeof import('./components/counter.vue')['default']
    Education: typeof import('./components/education.vue')['default']
    Input: typeof import('./components/input.vue')['default']
    ProjectsCarousel: typeof import('./components/projects-carousel.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Welcome: typeof import('./components/welcome.vue')['default']
  }
}
